[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
base         = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base         = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
